# Generated by Django 5.2.6 on 2025-10-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion_horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ao_lanzamiento', models.IntegerField()),
            ],
            options={
                'db_table': 'videojuegos',
            },
        ),
    ]
